# Generated by Django 5.1.7 on 2025-08-06 07:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mang', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='password',
        ),
        migrations.AddField(
            model_name='custom_user',
            name='device_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='email_pin',
            field=models.PositiveSmallIntegerField(blank=True, help_text='5-digit email verification PIN', null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='email_pin_created',
            field=models.DateTimeField(blank=True, help_text='When the PIN was generated', null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Has the user verified their email?'),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Is the user account archived?'),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='is_visitor',
            field=models.BooleanField(default=False, help_text='Is this user a guest/visitor?'),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='profile_email_pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='profile_email_pin_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='profile_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='user_password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='biometric_enabled',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='email',
            field=models.EmailField(default='default@temp.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
