# Generated by Django 5.1.7 on 2025-08-13 19:19

import user_mang.models.custom_user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mang', '0002_remove_visitor_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='custom_user',
            managers=[
                ('objects', user_mang.models.custom_user.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='custom_user',
            name='login_otp',
            field=models.CharField(blank=True, help_text='Transient OTP for passwordless login', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='login_otp_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='login_otp_last_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='login_otp_sent_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of OTPs sent in current rate window'),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='related_devices',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='temp_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='user_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
