# Generated by Django 5.1.7 on 2025-08-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mang', '0003_alter_custom_user_managers_custom_user_login_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='is_google_user',
            field=models.BooleanField(default=False, help_text='Account created / linked via Google OAuth'),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='is_openrouter_user',
            field=models.BooleanField(default=False, help_text='Account created / linked via OpenRouter OAuth'),
        ),
    ]
