# Generated by Django 5.1.7 on 2026-07-07 09:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthState',
            fields=[
                ('oauth_state_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('openrouter', 'OpenRouter'), ('google', 'Google'), ('github', 'GitHub'), ('microsoft', 'Microsoft')], max_length=32)),
                ('state', models.CharField(db_index=True, max_length=128, unique=True)),
                ('code_challenge', models.CharField(max_length=256)),
                ('code_verifier', models.CharField(blank=True, max_length=256, null=True)),
                ('redirect_uri', models.CharField(blank=True, max_length=512, null=True)),
                ('mobile_redirect', models.CharField(blank=True, max_length=512, null=True)),
                ('result_payload', models.TextField(blank=True, null=True)),
                ('result_retrieved', models.BooleanField(default=False)),
                ('scope', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderOAuthToken',
            fields=[
                ('provider_oauth_token_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('openrouter', 'OpenRouter'), ('google', 'Google'), ('github', 'GitHub'), ('microsoft', 'Microsoft')], db_index=True, max_length=32)),
                ('provider_account_id', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_type', models.CharField(blank=True, max_length=32, null=True)),
                ('scope', models.CharField(blank=True, max_length=512, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
