# Generated by Django 5.1.7 on 2026-07-07 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthstate',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oauth_states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='provideroauthtoken',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='provideroauthtoken',
            unique_together={('provider', 'provider_account_id'), ('user_id', 'provider')},
        ),
    ]
