# Generated by Django 5.1.7 on 2025-08-24 22:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_oauthstate_result_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='oauthstate',
            old_name='used',
            new_name='is_used',
        ),
        migrations.RenameField(
            model_name='oauthstate',
            old_name='id',
            new_name='oauth_state_id',
        ),
        migrations.RenameField(
            model_name='oauthstate',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='provideroauthtoken',
            old_name='id',
            new_name='provider_oauth_token_id',
        ),
        migrations.RenameField(
            model_name='provideroauthtoken',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterUniqueTogether(
            name='provideroauthtoken',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='oauthstate',
            name='provider',
            field=models.CharField(choices=[('openrouter', 'OpenRouter'), ('google', 'Google'), ('github', 'GitHub'), ('microsoft', 'Microsoft')], max_length=32),
        ),
        migrations.AlterField(
            model_name='provideroauthtoken',
            name='provider',
            field=models.CharField(choices=[('openrouter', 'OpenRouter'), ('google', 'Google'), ('github', 'GitHub'), ('microsoft', 'Microsoft')], db_index=True, max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='provideroauthtoken',
            unique_together={('user_id', 'provider')},
        ),
    ]
