# Generated by Django 5.1.7 on 2025-08-28 17:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0004_rename_used_oauthstate_is_used_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='provideroauthtoken',
            unique_together={('user_id', 'provider')},
        ),
        migrations.AddField(
            model_name='provideroauthtoken',
            name='provider_account_id',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='provideroauthtoken',
            unique_together={('provider', 'provider_account_id'), ('user_id', 'provider')},
        ),
    ]
