# Generated by Django 5.1.7 on 2025-08-13 19:25

import chat_api.models.message
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_type', models.CharField(blank=True, default='message', max_length=50, null=True)),
                ('output_id', models.CharField(blank=True, max_length=255, null=True)),
                ('output_status', models.CharField(blank=True, max_length=50, null=True)),
                ('output_role', models.CharField(blank=True, max_length=50, null=True)),
                ('output_content_type', models.CharField(blank=True, max_length=50, null=True)),
                ('output_content_text', models.TextField(blank=True, null=True)),
                ('output_content_annotations', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_model', models.CharField(blank=True, max_length=255, null=True)),
                ('request_input', models.TextField(blank=True, null=True)),
                ('request_system_role', models.CharField(blank=True, max_length=50, null=True)),
                ('request_system_content', models.TextField(blank=True, null=True)),
                ('request_system_prompt', models.TextField(blank=True, null=True)),
                ('request_use_structured_output', models.BooleanField(blank=True, null=True)),
                ('request_structured_schema', models.TextField(blank=True, null=True)),
                ('request_user_role', models.CharField(blank=True, max_length=50, null=True)),
                ('request_user_content', models.TextField(blank=True, null=True)),
                ('request_min_p', models.FloatField(blank=True, null=True)),
                ('request_temperature', models.FloatField(blank=True, null=True)),
                ('request_top_p', models.FloatField(blank=True, null=True)),
                ('request_n', models.IntegerField(blank=True, null=True)),
                ('request_top_k', models.IntegerField(blank=True, null=True)),
                ('request_stream', models.BooleanField(default=False)),
                ('request_stop', models.TextField(blank=True, null=True)),
                ('request_max_tokens', models.IntegerField(blank=True, null=True)),
                ('repeat_penalty', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageResponse',
            fields=[
                ('response_id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('object', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('error', models.TextField(blank=True, default='null', null=True)),
                ('incomplete_details', models.TextField(blank=True, default='null', null=True)),
                ('max_output_tokens', models.IntegerField(blank=True, default='null', null=True)),
                ('model', models.CharField(blank=True, default='unassigned', max_length=255, null=True)),
                ('parallel_tool_calls', models.BooleanField(default=False)),
                ('previous_response_id', models.CharField(blank=True, default='unassigned', max_length=255, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('reasoning_effort', models.TextField(blank=True, default='null', null=True)),
                ('reasoning_summary', models.TextField(blank=True, default='null', null=True)),
                ('store', models.BooleanField(default=True)),
                ('temperature', models.FloatField(blank=True, default=1.0, null=True)),
                ('text_format_type', models.CharField(blank=True, max_length=50, null=True)),
                ('tool_choice', models.CharField(blank=True, max_length=255, null=True)),
                ('tools', models.TextField(blank=True, null=True)),
                ('top_p', models.FloatField(blank=True, null=True)),
                ('truncation', models.CharField(blank=True, max_length=50, null=True)),
                ('usage_input_tokens', models.IntegerField(blank=True, null=True)),
                ('usage_output_tokens', models.IntegerField(blank=True, null=True)),
                ('usage_total_tokens', models.IntegerField(blank=True, null=True)),
                ('user', models.CharField(blank=True, default='null', max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conversation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, default='Title', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_only', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('has_image', models.BooleanField(default=False)),
                ('img_Url', models.ImageField(blank=True, null=True, upload_to='message_images/', validators=[chat_api.models.message.validate_image_size])),
                ('metadata', models.JSONField(blank=True, null=True, validators=[chat_api.models.message.validate_metadata_size])),
                ('has_embedding', models.BooleanField(default=False)),
                ('has_document', models.BooleanField(default=False)),
                ('doc_url', models.FileField(blank=True, null=True, upload_to='message_docs/', validators=[chat_api.models.message.validate_document_size])),
                ('vote', models.BooleanField(blank=True, default=False, null=True)),
                ('conversation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat_api.conversation')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
                ('output_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='chat_api.messageoutput')),
                ('request_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='chat_api.messagerequest')),
                ('response_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='chat_api.messageresponse')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
