# Generated by Django 5.1.7 on 2025-08-15 17:32

import chat_api.models.attachment
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=32)),
                ('mime_type', models.CharField(blank=True, max_length=128, null=True)),
                ('file_path', models.CharField(blank=True, help_text='Server-side storage path or external URL', max_length=512, null=True)),
                ('encrypted_blob', models.FileField(blank=True, help_text='Encrypted ciphertext blob uploaded by client', null=True, upload_to=chat_api.models.attachment.encrypted_upload_path)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('enc_algo', models.CharField(blank=True, max_length=32, null=True)),
                ('iv_base64', models.CharField(blank=True, max_length=64, null=True)),
                ('key_ref', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat_api.conversation')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat_api.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attachment',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='attach_conv_created_idx'), models.Index(fields=['message'], name='attach_message_idx')],
            },
        ),
    ]
