# Generated by Django 5.1.7 on 2025-08-24 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0002_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation_id',
        ),
        migrations.AddField(
            model_name='conversation',
            name='message_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='chat_api.message'),
        ),
    ]
