# Generated by Django 5.1.7 on 2025-08-24 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0003_remove_message_conversation_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attachment',
            name='attach_conv_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='attachment',
            name='attach_message_idx',
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='id',
            new_name='attachment_id',
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='message',
            new_name='message_id',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='message_id',
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat_api.conversation'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['message_id', 'created_at'], name='attach_message_created_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['message_id'], name='attach_message_idx'),
        ),
    ]
