# Generated by Django 5.1.7 on 2025-08-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0004_remove_attachment_attach_conv_created_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messageresponse',
            old_name='model',
            new_name='model_name',
        ),
        migrations.AlterField(
            model_name='messageresponse',
            name='max_output_tokens',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
