# Generated by Django 5.1.7 on 2025-09-18 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0005_rename_model_messageresponse_model_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='conversation',
            new_name='conversation_id',
        ),
        migrations.RenameField(
            model_name='messagerequest',
            old_name='request_use_structured_output',
            new_name='request_user_structured_output',
        ),
    ]
