alerts:
- rule: DEPLOYMENT_FAILED
- rule: DEPLOYMENT_LIVE
- rule: DEPLOYMENT_STARTED
domains:
- domain: itse500-ok.ly
  type: PRIMARY
  zone: itse500-ok.ly
- domain: www.itse500-ok.ly
  type: ALIAS
  zone: itse500-ok.ly
ingress:
  rules:
  - component:
      name: web
    match:
      path:
        prefix: /
name: itse500-django
region: fra
services:
- build_command: |
    pip install -r requirements.txt
    python manage.py makemigrations auth_api user_mang chat_api crypto_api
    python manage.py migrate --noinput
  environment_slug: python
  envs:
  - key: MAILEROO_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: ***************************d3510e0c5a4228c84fb
  - key: ZERUH_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: ***************************7b7d8784911e66cf
  - key: DJANGO_SETTINGS_MODULE
    scope: RUN_AND_BUILD_TIME
    value: prompeteer_server.settings
  - key: SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1***************************]
  - key: DEBUG
    scope: RUN_AND_BUILD_TIME
    value: "False"
  - key: OPENROUTER_PROVISIONING_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:I***************************]
  - key: MS_CLIENT_ID
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:bZ***************************]
  - key: MS_CLIENT_SECRET
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:***************************]
  - key: GITHUB_CLIENT_ID
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:1***************************]
  - key: GITHUB_CLIENT_SECRET
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:***************************]
  - key: GOOGLE_OAUTH_CLIENT_ID
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:***************************]
  - key: GOOGLE_OAUTH_CLIENT_SECRET
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:***************************]
  - key: BACKEND_PASSWORD_SALT
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:***************************]
  - key: ALLOWED_HOSTS
    scope: RUN_AND_BUILD_TIME
    value: '["itse500-ok.ly", "www.itse500-ok.ly", "157.230.29.188", "188.166.193.176"]'
  github:
    branch: main
    repo: arousi/ITSE500-Django
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: web
  run_command: |
    gunicorn prompeteer_server.wsgi:application
    python manage.py makemigrations auth_api user_mang chat_api crypto_api
    python manage.py migrate --noinput
