# Generated by Django 5.1.7 on 2026-07-07 09:51

import django.contrib.auth.validators
import django.utils.timezone
import user_mang.models.custom_user
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_visitor', models.BooleanField(default=False, help_text='Is this user a guest/visitor?')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('biometric_enabled', models.BooleanField(blank=True, default=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user_password', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('devices_id', models.JSONField(blank=True, max_length=128, null=True)),
                ('temp_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('related_devices', models.JSONField(blank=True, default=list)),
                ('email_pin', models.PositiveSmallIntegerField(blank=True, help_text='5-digit email verification PIN', null=True)),
                ('email_pin_created', models.DateTimeField(blank=True, help_text='When the PIN was generated', null=True)),
                ('email_verified', models.BooleanField(default=False, help_text='Has the user verified their email?')),
                ('is_archived', models.BooleanField(default=False, help_text='Is the user account archived?')),
                ('login_otp', models.CharField(blank=True, help_text='Transient OTP for passwordless login', max_length=10, null=True)),
                ('login_otp_created', models.DateTimeField(blank=True, null=True)),
                ('login_otp_sent_count', models.PositiveIntegerField(default=0, help_text='Number of OTPs sent in current rate window')),
                ('login_otp_last_sent', models.DateTimeField(blank=True, null=True)),
                ('is_google_user', models.BooleanField(default=False, help_text='Account created / linked via Google OAuth')),
                ('is_openrouter_user', models.BooleanField(default=False, help_text='Account created / linked via OpenRouter OAuth')),
                ('is_microsoft_user', models.BooleanField(default=False, help_text='Account created / linked via Microsoft OAuth')),
                ('is_github_user', models.BooleanField(default=False, help_text='Account created / linked via GitHub OAuth')),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', user_mang.models.custom_user.CustomUserManager()),
            ],
        ),
    ]
