# Generated by Django 5.1.7 on 2025-08-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mang', '0004_custom_user_is_google_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='totp_secret',
            field=models.CharField(blank=True, help_text='TOTP secret for two-factor authentication app', max_length=32, null=True),
        ),
    ]
