# Generated by Django 5.1.7 on 2025-08-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mang', '0005_custom_user_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='is_github_user',
            field=models.BooleanField(default=False, help_text='Account created / linked via GitHub OAuth'),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='is_microsoft_user',
            field=models.BooleanField(default=False, help_text='Account created / linked via Microsoft OAuth'),
        ),
    ]
