# Generated by Django 5.1.7 on 2025-08-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mang', '0006_custom_user_is_github_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='profile_email_pin',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='profile_email_pin_created',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='profile_email_verified',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='totp_secret',
        ),
        migrations.AddField(
            model_name='custom_user',
            name='devices_id',
            field=models.JSONField(blank=True, max_length=128, null=True),
        ),
    ]
