# Generated by Django 5.1.7 on 2026-07-07 09:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserKeyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umk_b64', models.TextField(help_text='Base64 encoded 32-byte user master key')),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Key Material',
                'verbose_name_plural': 'User Key Materials',
                'db_table': 'user_key_material',
            },
        ),
    ]
