# Generated by Django 5.1.7 on 2025-08-24 12:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKeyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umk_b64', models.TextField(help_text='Base64 encoded 32-byte user master key')),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='key_material', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Key Material',
                'verbose_name_plural': 'User Key Materials',
                'db_table': 'user_key_material',
            },
        ),
    ]
