# Generated by Django 5.1.7 on 2025-08-24 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userkeymaterial',
            old_name='user',
            new_name='user_id',
        ),
    ]
