from datetime import timedelta
from pathlib import Path
import os
import importlib.util as _imp
import mimetypes
import warnings
from django.core.exceptions import ImproperlyConfigured

# --- Early .env loader (supports lines starting with `set `) ---
BASE_DIR = Path(__file__).resolve().parent.parent

def _load_simple_env(env_path: Path):
    try:
        with env_path.open('r', encoding='utf-8') as fh:
            for raw in fh:
                line = raw.strip()
                if not line or line.startswith('#'):
                    continue
                if line.lower().startswith('set '):  # Windows style in provided .env
                    line = line[4:].strip()
                if '=' not in line:
                    continue
                k, v = line.split('=', 1)
                k = k.strip()
                v = v.strip().strip('"').strip("'")
                # Don't override if already exported in real environment
                if k and k not in os.environ:
                    os.environ[k] = v
    except FileNotFoundError:
        pass

_load_simple_env(BASE_DIR / '.env')
# ---------------------------------------------------------------
# settings.py
# SECURITY: previously a hardcoded literal; moved to env (no fallback value, see .env.example).
ZERUH_API_KEY = os.getenv('ZERUH_API_KEY', '')

EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND')
EMAIL_HOST = os.environ.get('EMAIL_HOST')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL')

#* app.yaml in production will take precedence than .env
# Read env AFTER loading
GOOGLE_OAUTH_CLIENT_ID = os.getenv('GOOGLE_OAUTH_CLIENT_ID','')
GOOGLE_OAUTH_CLIENT_SECRET = os.getenv('GOOGLE_OAUTH_CLIENT_SECRET','')
GOOGLE_OAUTH_REDIRECT_URI = os.getenv('GOOGLE_OAUTH_REDIRECT_URI','')
GOOGLE_OAUTH_REDIRECT_URI_SSR = os.getenv('GOOGLE_OAUTH_REDIRECT_URI_SSR','')

# Provide local dev fallbacks if still empty (avoids 400 during manual tests)
if not GOOGLE_OAUTH_REDIRECT_URI:
    GOOGLE_OAUTH_REDIRECT_URI = 'http://127.0.0.1:8000/api/v1/auth_api/google/callback/'
if not GOOGLE_OAUTH_REDIRECT_URI_SSR:
    GOOGLE_OAUTH_REDIRECT_URI_SSR = 'http://127.0.0.1:8000/api/v1/auth_api/google/callback/ssr/'

# Normalize: Django URL patterns include trailing slash, so ensure env values do too
if GOOGLE_OAUTH_REDIRECT_URI and not GOOGLE_OAUTH_REDIRECT_URI.endswith('/'):
    GOOGLE_OAUTH_REDIRECT_URI = GOOGLE_OAUTH_REDIRECT_URI + '/'
if GOOGLE_OAUTH_REDIRECT_URI_SSR and not GOOGLE_OAUTH_REDIRECT_URI_SSR.endswith('/'):
    GOOGLE_OAUTH_REDIRECT_URI_SSR = GOOGLE_OAUTH_REDIRECT_URI_SSR + '/'

# OpenRouter
OPENROUTER_CLIENT_ID = os.getenv('OPENROUTER_CLIENT_ID', '')
OPENROUTER_CLIENT_SECRET = os.getenv('OPENROUTER_CLIENT_SECRET', '')
OPENROUTER_REDIRECT_URI = os.getenv('OPENROUTER_REDIRECT_URI', '')

# GitHub
GITHUB_CLIENT_ID = os.getenv('GITHUB_CLIENT_ID', '')
GITHUB_CLIENT_SECRET = os.getenv('GITHUB_CLIENT_SECRET', '')
GITHUB_REDIRECT_URI = os.getenv('GITHUB_REDIRECT_URI', '')

# Microsoft
MS_CLIENT_ID = os.getenv('MS_CLIENT_ID', '')
MS_CLIENT_SECRET = os.getenv('MS_CLIENT_SECRET', '')
MS_REDIRECT_URI = os.getenv('MS_REDIRECT_URI', '')

# --- DEBUG must be known before the fail-fast secret checks below ---
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False').lower() in ('1', 'true', 'yes')

# --- Fail-fast secrets: no insecure production fallback ---
# BACKEND_PASSWORD_SALT: required in production; ephemeral dev-only default when DEBUG=True.
_backend_password_salt_env = os.getenv('BACKEND_PASSWORD_SALT')
if _backend_password_salt_env:
    BACKEND_PASSWORD_SALT = _backend_password_salt_env
elif DEBUG:
    BACKEND_PASSWORD_SALT = 'EPHEMERAL-DEV-ONLY-SALT-DO-NOT-USE-IN-PRODUCTION'
    warnings.warn(
        "BACKEND_PASSWORD_SALT not set; using an ephemeral dev-only default because DEBUG=True. "
        "Set BACKEND_PASSWORD_SALT in the environment before deploying.",
        RuntimeWarning,
    )
else:
    raise ImproperlyConfigured(
        "BACKEND_PASSWORD_SALT environment variable is required when DEBUG=False."
    )

"""
Django settings for prompeteer_server project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Fail-fast: no insecure production fallback. DEBUG was already resolved above.
_secret_key_env = os.getenv('SECRET_KEY')
if _secret_key_env:
    SECRET_KEY = _secret_key_env
elif DEBUG:
    SECRET_KEY = 'django-insecure-EPHEMERAL-DEV-ONLY-KEY-DO-NOT-USE-IN-PRODUCTION'
    warnings.warn(
        "SECRET_KEY not set; using an ephemeral dev-only default because DEBUG=True. "
        "Set SECRET_KEY in the environment before deploying.",
        RuntimeWarning,
    )
else:
    raise ImproperlyConfigured(
        "SECRET_KEY environment variable is required when DEBUG=False."
    )

_DEFAULT_ALLOWED = [
    'react.itse500-ok.ly',
    '127.0.0.1',
    'itse500-ok.ly',
    'www.itse500-ok.ly',
    '157.230.29.188',
    'localhost',
    'grad-project-server-tq36w.ondigitalocean.app',
    'flutter.itse500-ok.ly',
]

# Allow overriding allowed hosts via environment (comma-separated)
_env_allowed = os.getenv('ALLOWED_HOSTS')
if _env_allowed:
    ALLOWED_HOSTS = [h.strip() for h in _env_allowed.split(',') if h.strip()]
else:
    ALLOWED_HOSTS = _DEFAULT_ALLOWED


# Application definition
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Throttling: global anon rate + a strict 'auth' scope for brute-force protection.
    # Brute-forceable auth views (Login, Register, EmailPinVerify, SetPasswordAfterEmailVerify,
    # SendLoginOTP, VerifyLoginOTP, LoginWithOTP) declare throttle_scope = 'auth' to apply the
    # stricter 'auth' rate below via ScopedRateThrottle.
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/min',
        'auth': '10/min',
    },
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

SIMPLE_JWT = {
    # JWT hardening: short-lived access token, rotated refresh tokens, blacklist on rotation.
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.getenv('JWT_ACCESS_MINUTES', '15'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv('JWT_REFRESH_DAYS', '7'))),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'USER_ID_FIELD': 'user_id',
    'USER_ID_CLAIM': 'user_id',
}

AUTH_USER_MODEL = 'user_mang.Custom_User'


_HAS_JAZZMIN = _imp.find_spec('jazzmin') is not None
_HAS_SILK = _imp.find_spec('silk') is not None
_HAS_DEBUG_TOOLBAR = _imp.find_spec('debug_toolbar') is not None
_HAS_SPECTACULAR = _imp.find_spec('drf_spectacular') is not None

INSTALLED_APPS = [
    *(['jazzmin'] if _HAS_JAZZMIN else []),
    'prompeteer_server',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'auth_api',
    'channels', # for real-time mssgs
    "user_mang",
    "chat_api",
    "crypto_api",
    "rest_framework",
    'rest_framework_simplejwt.token_blacklist',
    *(['drf_spectacular'] if _HAS_SPECTACULAR else []),

]

# Shared Redis URL used by CACHES, CHANNEL_LAYERS, and Celery below.
# Defined here (before first use) so its fallback (LocMemCache /
# InMemoryChannelLayer / synchronous Celery) applies with zero infra env vars set.
REDIS_URL = os.getenv('REDIS_URL', '')

# Channel layer: env-gated on REDIS_URL. Uses channels_redis (third-party,
# only imported when REDIS_URL is set) so real-time messaging fans out across
# multiple worker processes/machines in production. Falls back to the
# in-memory channel layer that ships with `channels` itself (no extra
# dependency, single-process only) for local dev / the pytest suite.
if REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [REDIS_URL],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }
#* Logging in Deployment

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'with_newline': {
            '()': 'logging.Formatter',
            'format': '%(asctime)s\t|\t%(levelname)s\t|\t%(name)s\t|\t%(message)s',
        },
        'a4_wrap': {
            '()': 'prompeteer_server.utils.logging.A4WrapFormatter',
            'format': '%(asctime)s\t|\t%(levelname)s\t|\t%(name)s\t|\t%(message)s',
        },
    },
    'handlers': {
        'console': {  # <-- Add this handler
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'with_newline',  # or 'a4_wrap' if you want your custom formatting
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'user_mang.log'),
            'formatter': 'a4_wrap',
        },
        'chat_api_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'chat_api.log'),
            'formatter': 'a4_wrap',
        },
        'conversation_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'conversation.log'),
            'formatter': 'a4_wrap',
        },
        'auth_api_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'auth_api.log'),
            'formatter': 'a4_wrap',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],  # <-- Add 'console'
            'level': 'INFO',
            'propagate': True,
        },
        'auth_api': {
            'handlers': ['console', 'auth_api_file'],  # <-- Add 'console'
            'level': 'INFO',
            'propagate': False,
        },
        'user_mang': {
            'handlers': ['console', 'file'],  # <-- Add 'console'
            'level': 'INFO',
            'propagate': False,
        },
        'chat_api': {
            'handlers': ['console', 'chat_api_file'],  # <-- Add 'console'
            'level': 'INFO',
            'propagate': False,
        },
        'conversation': {
            'handlers': ['console', 'conversation_file'],  # <-- Add 'console'
            'level': 'INFO',
            'propagate': False,
        },
    },
}


#* Logging in Debug mode
""" 
# Dynamically create log file path within the app's directory
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'with_newline': {
            '()': 'logging.Formatter',
            'format': '%(asctime)s\t|\t%(levelname)s\t|\t%(name)s\t|\t%(message)s',
        },
        'a4_wrap': {
            '()': 'prompeteer_server.utils.logging.A4WrapFormatter',
            'format': '%(asctime)s\t|\t%(levelname)s\t|\t%(name)s\t|\t%(message)s',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'user_mang.log'),
            'formatter': 'a4_wrap',
        },
        'chat_api_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'chat_api.log'),
            'formatter': 'a4_wrap',
        },
        'conversation_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'conversation.log'),
            'formatter': 'a4_wrap',
        },
        'auth_api_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'auth_api.log'),
            'formatter': 'a4_wrap',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'auth_api': {
            'handlers': ['auth_api_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'user_mang': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        },
        'chat_api': {
            'handlers': ['chat_api_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'conversation': {
            'handlers': ['conversation_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
} """

"""
"default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
    """
ASGI_APPLICATION = "prompeteer_server.asgi.application"

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'prompeteer_server.middleware.DebugHeadersMiddleware',
]

# Insert Silk first when DEBUG for full coverage, and Debug Toolbar after common middleware
if DEBUG:
    if _HAS_SILK:
        INSTALLED_APPS += ['silk']
        MIDDLEWARE = ['silk.middleware.SilkyMiddleware'] + MIDDLEWARE
    if _HAS_DEBUG_TOOLBAR:
        INSTALLED_APPS += ['debug_toolbar']
        insert_after = 'django.middleware.common.CommonMiddleware'
        try:
            idx = MIDDLEWARE.index(insert_after) + 1
            MIDDLEWARE = MIDDLEWARE[:idx] + ['debug_toolbar.middleware.DebugToolbarMiddleware'] + MIDDLEWARE[idx:]
        except ValueError:
            MIDDLEWARE.append('debug_toolbar.middleware.DebugToolbarMiddleware')

## CORS
# Allow production site and flexible localhost during development/testing
CORS_ALLOWED_ORIGINS = [
    # Production web origins (HTTPS)
    "https://www.itse500-ok.ly",
    "https://itse500-ok.ly",
    "https://react.itse500-ok.ly",
    "https://flutter.itse500-ok.ly",
]

# Permit any localhost/127.0.0.1 with any port (for Flutter web dev servers)
CORS_ALLOWED_ORIGIN_REGEXES = [

    r"^http://localhost(:\d+)?$",
    r"^http://127\.0\.0\.1(:\d+)?$",
]

# In debug, you may allow all origins; keep strict in production
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True

    # Allow common headers used by the SPA, including Authorization for JWT
from corsheaders.defaults import default_headers, default_methods
CORS_ALLOW_HEADERS = list(default_headers) + [
    'authorization',
    'content-type',
]

# Standard methods (includes OPTIONS automatically)
CORS_ALLOW_METHODS = list(default_methods)

# Expose token refresh headers to the browser if set by the API
CORS_EXPOSE_HEADERS = [
    'X-New-Access-Token',
    'X-New-Refresh-Token',
]

# Cache preflight results to reduce OPTIONS traffic
CORS_PREFLIGHT_MAX_AGE = 86400

ROOT_URLCONF = 'prompeteer_server.urls'

SPECTACULAR_SETTINGS = {
    'TITLE': 'ITSE500 APIs Documentation',
    'DESCRIPTION': 'Authentication, Chat, and User Management API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'COMPONENT_SECURITY_SCHEMES': {
        'BearerAuth': {
            'type': 'http',
            'scheme': 'bearer',
            'bearerFormat': 'JWT',
        }
    },
    'SECURITY': [
        {'BearerAuth': []}
    ],
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,
        'displayOperationId': True,
    },
}

if DEBUG:
    INTERNAL_IPS = [
        '127.0.0.1', 'localhost',
    ]
    # Let WhiteNoise use staticfiles finders in development
    WHITENOISE_USE_FINDERS = True

JAZZMIN_SETTINGS = {
    "site_title": "ITSE500 Admin",
    "site_header": "ITSE500 Admin",
    "welcome_sign": "Welcome to ITSE500 Admin",
}

# If using cookie auth or CSRF-protected endpoints from the SPA, trust these origins
CSRF_TRUSTED_ORIGINS = [
    'https://itse500-ok.ly',
    'https://www.itse500-ok.ly',
    'https://react.itse500-ok.ly',
    'https://flutter.itse500-ok.ly',
]


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
            BASE_DIR / 'staticfiles' / 'templates',
            BASE_DIR / 'frontend_build',
            BASE_DIR / 'flutter_build',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'prompeteer_server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Env-gated: if DB_HOST or DB_ENGINE is set, use PostgreSQL (psycopg v3 driver);
# otherwise fall back to the local SQLite file (no extra dependency required).
# This keeps local dev + the pytest suite working with zero infra env vars set,
# since `psycopg` is not installed in that environment.
_db_host = os.getenv('DB_HOST')
_db_engine_override = os.getenv('DB_ENGINE')
if _db_host or _db_engine_override:
    _db_ssl = os.getenv('DB_SSL', 'False').lower() in ('1', 'true', 'yes')
    DATABASES = {
        'default': {
            'ENGINE': _db_engine_override or 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'prompeteer_db'),
            'USER': os.getenv('DB_USER', 'prompeteer_user'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': _db_host or '127.0.0.1',
            'PORT': os.getenv('DB_PORT', '5432'),
            'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '60')),
            'OPTIONS': ({'sslmode': 'require'} if _db_ssl else {}),
        },
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        },
    }
# BACKEND_PASSWORD_SALT is already defined above (fail-fast from environment; see top of file).
# Keep it stable across restarts; do not override it here.

# Cache: env-gated on REDIS_URL (defined above). Uses Django's native Redis
# cache backend (no django-redis dependency needed). Falls back to in-process
# LocMemCache when REDIS_URL is unset, so no third-party backend is imported.
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'frontend_build' / 'static',
    ('flutter-web', BASE_DIR / 'flutter_build'),
]
# Media (uploaded encrypted blobs)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# STORAGES (Django 5.x): env-gated on AWS_S3_ENDPOINT_URL (MinIO/S3-compatible).
# When absent, `default` stays the built-in FileSystemStorage (MEDIA_ROOT above)
# and nothing from `django-storages`/`boto3` is imported, so those third-party
# packages are not required for local dev / the pytest suite.
# `staticfiles` stays on WhiteNoise in both cases.
AWS_S3_ENDPOINT_URL = os.getenv('AWS_S3_ENDPOINT_URL', '')
STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}
if AWS_S3_ENDPOINT_URL:
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID', '')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY', '')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME', '')
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'us-east-1')
    # Path-style addressing is required for MinIO (virtual-hosted-style needs
    # per-bucket DNS, which a self-managed MinIO instance won't have).
    AWS_S3_ADDRESSING_STYLE = 'path'
    # Files are served via signed/expiring query-string URLs by default since
    # the bucket is not assumed to be publicly readable.
    AWS_QUERYSTRING_AUTH = os.getenv('AWS_QUERYSTRING_AUTH', 'True').lower() in ('1', 'true', 'yes')
    STORAGES['default'] = {
        'BACKEND': 'storages.backends.s3.S3Storage',
    }
else:
    STORAGES['default'] = {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    }


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

# *django doesn't accept uuid as it is not a subclass of AutoField
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Ensure correct MIME for WASM (CanvasKit)
mimetypes.add_type('application/wasm', '.wasm', True)

# --- Production security headers (applied only when DEBUG=False) ---
# Deploys behind nginx, which terminates TLS and forwards X-Forwarded-Proto.
# SSL redirect + HSTS are the most disruptive to a local prod-like run without TLS,
# so they're additionally gated behind SECURE_SSL (defaults to True in production).
if not DEBUG:
    _secure_ssl = os.getenv('SECURE_SSL', 'True').lower() in ('1', 'true', 'yes')
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = _secure_ssl
    SECURE_HSTS_SECONDS = 31536000 if _secure_ssl else 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = _secure_ssl
    SECURE_HSTS_PRELOAD = _secure_ssl
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

# --- Celery (background task queue) ---
# Broker/result backend default to REDIS_URL (shared with CACHES/CHANNEL_LAYERS
# above) but can be pointed at a separate Redis instance/db via CELERY_BROKER_URL
# / CELERY_RESULT_BACKEND. When no broker is configured at all, tasks run
# synchronously in-process (CELERY_TASK_ALWAYS_EAGER) so `celery[redis]` is
# never required and `.delay()`/`.apply_async()` calls still work in local
# dev / the pytest suite without a running worker.
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', REDIS_URL)
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', REDIS_URL)
CELERY_TASK_ALWAYS_EAGER = not bool(CELERY_BROKER_URL)
CELERY_TASK_EAGER_PROPAGATES = True
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
